name: GitBook Versioning Automation

on:
  push:
    branches:
      - main 

jobs:
  api_request:
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run API request using PowerShell
        shell: pwsh
        run: |
          $url = "https://api.gitbook.com/v1/spaces/2MQHVPylci67MSGgaNm5/change-requests"
          $token = "gb_api_6nkWp1nowtq8GjpYqwD8WXjeEl1JGDNXceS4LvNV"

          $headers = @{
              "Authorization" = "Bearer $token"
              "Content-Type" = "application/json"
          }

          # Datos para la solicitud POST
          $body = @{
              "name" = "New Version"  # Nombre de la versión
              "description" = "This is the description of the new version."  # Descripción opcional
              "version" = "1.0.0"  # Número de versión, ajústalo según tu sistema de versionamiento
          } | ConvertTo-Json

          # Hacer la solicitud POST para crear un cambio de versión
          $response = Invoke-RestMethod -Uri $url -Method Post -Headers $headers -Body $body

          # Mostrar la respuesta en la consola
          Write-Output "Response from GitBook API:"
          Write-Output $response
