name: GitBook Version Release Sync

on:
  release:
    types: [published]

jobs:
  sync_version_with_gitbook:
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Create GitBook Version Change Request
        shell: pwsh
        run: |
          $url = "https://api.gitbook.com/v1/spaces/2MQHVPylci67MSGgaNm5/change-requests"
          $token = "gb_api_6nkWp1nowtq8GjpYqwD8WXjeEl1JGDNXceS4LvNV"

          # Obtener la versión y el título del release desde el evento de GitHub
          $versionName = "${{ github.event.release.tag_name }}"
          $description = "${{ github.event.release.body }}"
          
          # Establecer los encabezados y el cuerpo de la solicitud
          $headers = @{
              "Authorization" = "Bearer $token"
              "Content-Type" = "application/json"
          }

          # Crear el cuerpo de la solicitud para GitBook con versión y descripción
          $body = @{
              "name" = "Release: $versionName"
              "description" = $description
              "version" = $versionName
              "status" = "pending"
          } | ConvertTo-Json

          # Enviar la solicitud POST a GitBook
          $response = Invoke-RestMethod -Uri $url -Method Post -Headers $headers -Body $body

          # Mostrar la respuesta en la consola para verificar si fue exitoso
          Write-Output "Response from GitBook API:"
          Write-Output $response
