name: GitBook API Request

on:
  push:
    branches:
      - main 

jobs:
  api_request:
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run API request using PowerShell
        shell: pwsh
        run: |
          $url = "https://api.gitbook.com/v1/user"
          $token = "gb_api_6nkWp1nowtq8GjpYqwD8WXjeEl1JGDNXceS4LvNV"

          $headers = @{
              "Authorization" = "Bearer $token"
              "Content-Type" = "application/json"
          }

          $response = Invoke-RestMethod -Uri $url -Method Get -Headers $headers

          # Mostrar la respuesta en la consola
          Write-Output "Response from GitBook API:"
          Write-Output $response
