name: Update GitBook with GitHub Release

on:
  release:
    types: [published]

jobs:
  update_gitbook:
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Post Release Information to GitBook
        env:
          GITBOOK_TOKEN: gb_api_6nkWp1nowtq8GjpYqwD8WXjeEl1JGDNXceS4LvNV
        shell: pwsh
        run: |
          # Obtén la información del release desde GitHub Actions context
          $releaseName = "${{ github.event.release.name }}"
          $releaseBody = "${{ github.event.release.body }}"
          $spaceId = "2MQHVPylci67MSGgaNm5"
          $url = "https://api.gitbook.com/v1/spaces/$spaceId/content"

          # Estructura del JSON para crear una nueva página
          $body = @{
              "title" = "Release: $releaseName"
              "description" = "Detalles del Release en GitHub: $releaseBody"
              "blocks" = @(
                  @{
                      "type" = "markdown"
                      "data" = @{
                          "text" = "# $releaseName`n`n$releaseBody"
                      }
                  }
              )
          } | ConvertTo-Json -Depth 3

          # Encabezados para la autenticación y tipo de contenido
          $headers = @{
              "Authorization" = "Bearer $env:GITBOOK_TOKEN"
              "Content-Type"  = "application/json"
          }

          # Realiza la solicitud POST para crear la página
          $response = Invoke-RestMethod -Uri $url -Method POST -Headers $headers -Body $body

          # Muestra la respuesta en la consola para verificación
          Write-Output "Response from GitBook API:"
          Write-Output $response
