name: Versionado Automático con Jira

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checar el repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependencias
        run: npm install

      - name: Obtener tareas de Jira y actualizar la versión
        env:
          JIRA_USERNAME: ${{ secrets.ronaldpelaez201 }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_DOMAIN: 'ronaldpelaez201.atlassian.net'
        run: |
          # 1. Configura autenticación básica para Jira
          auth=$(echo "$ronaldpelaez201:$JIRA_API_TOKEN" | base64)

          # 2. Obtén los tickets de Jira en un JSON y filtra por alguna condición específica (proyecto, etc.)
          jira_tickets=$(curl -s -X GET \
            -H "Authorization: Basic $auth" \
            -H "Content-Type: application/json" \
            "https://$ronaldpelaez201/rest/api/3/search?jql=project=INMO AND status=Done&fields=key,summary" )

          # 3. Agrega numeración de versión y tickets
          version_message="Versión Automática - Incluye: "
          for ticket in $(echo "$jira_tickets" | jq -r '.issues[] | .key'); do
            version_message+="$ticket, "
          done

          # 4. Incrementa la versión y asocia tickets de Jira
          npm version patch -m "$version_message"
          git push --follow-tags

      - name: Actualizar documentación en GitBook
        run: |
          # Verifica que GitBook esté sincronizado con el repositorio para actualizarse automáticamente.
