name: Actualizar Documento en GitBook

on:
  push:
    branches:
      - main

jobs:
  update_gitbook_document:
    runs-on: windows-latest
    steps:
      - name: Ejecutar script de actualización
        shell: cmd
        run: |
          set DOCUMENT_ID=2MQHVPylci67MSGgaNm5
          set API_URL=https://api.gitbook.com/v1/spaces/2MQHVPylci6/documents/%DOCUMENT_ID%
          set DATA={"status":"published","version":"1.0","title":"Nueva Versión del Documento","content":"Este es el contenido actualizado del documento."}

          curl -X PUT "%API_URL%" ^
          -H "Content-Type: application/json" ^
          -d "%DATA%"
