name: Actualizar versión en GitBook

on:
  push:
    tags:
      - 'v*.*.*'  # Detecta etiquetas de versión en el formato v1.0.0, v2.1.0, etc.

jobs:
  deploy_gitbook:
    runs-on: windows-latest  # Especifica el entorno de Windows

    steps:
      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Publicar en GitBook
        env:
          GITBOOK_TOKEN: ${{ secrets.GITBOOK_TOKEN }}
        run: |
          set VERSION=$(git describe --tags)  # Obtiene la última etiqueta de versión
          echo Version: %VERSION%

          # Llamada a la API de GitBook para actualizar la versión
          curl -X POST https://api.gitbook.com/v1/spaces/2MQHVPylci67MSGgaNm5/documents ^
            -H "Authorization: Bearer %GITBOOK_TOKEN%" ^
            -H "Content-Type: application/json" ^
            -d "{\"title\": \"Versión %VERSION%\", \"description\": \"Documentación actualizada para la versión %VERSION%\", \"status\": \"published\"}"
