name: versionamiento automatico con Jira

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: windows-latest

    steps:
      - name: Checar el repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependencias
        run: npm install

      - name: Obtener tareas de Jira y actualizar la versi칩n
        run: |
          $JIRA_DOMAIN = 'ronaldpelaez201.atlassian.net'
          $JIRA_USER = 'Ronald Pel치ez' 
          
          # Realizar la solicitud a Jira
          $jira_tickets = Invoke-RestMethod -Uri "https://$JIRA_DOMAIN/rest/api/3/search?jql=project=inmobiliaria AND status=Done&fields=key,summary" -Method Get -ContentType "application/json"

          $version_message = "Versi칩n Autom치tica - Incluye: "
          foreach ($ticket in $jira_tickets.issues) {
            $version_message += "$($ticket.key), "
          }

          npm version patch -m $version_message
          git push --follow-tags
