name: Actualizar versión en GitBook

on:
  push:
    tags:
      - 'v*.*.*'  # Detecta etiquetas de versión en el formato v1.0.0, v2.1.0, etc.

jobs:
  deploy_gitbook:
    runs-on: windows-latest  # Especifica el entorno de Windows

    steps:
      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Obtener la versión
        shell: cmd
        id: get_version
        run: |
          for /f "tokens=*" %%i in ('git describe --tags') do set version=%%i
          echo Versión: %version%
          echo "::set-output name=version::%version%"

      - name: Publicar en GitBook usando cmd
        env:
          GITBOOK_TOKEN: ${{ secrets.GITBOOK_TOKEN }}
        shell: cmd
        run: |
          set AUTH_HEADER=Authorization: Bearer %GITBOOK_TOKEN%
          set CONTENT_TYPE=Content-Type: application/json
          set BODY={"title":"Documentación para la versión %VERSION%","description":"Actualización a la versión %VERSION%","status":"published"}

          curl -X PUT "https://api.gitbook.com/v1/spaces/eh4kfckVJvaoAnc26l7N/documents/2MQHVPylci67MSGgaNm5" ^
          -H "%AUTH_HEADER%" ^
          -H "%CONTENT_TYPE%" ^
          -d "%BODY%"
